// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
     return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzMGuLO0bMuC5nMiWF1DQK_3hc1xePh5s',
    appId: '1:568002325053:android:c5a5d0b6d733ed02b01854',
    messagingSenderId: '568002325053',
    projectId: 'gitlauk-e752f',
    storageBucket: 'gitlauk-e752f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfOpa7eAQRHVLRwb2TLdkcvutNA3EPqcI',
    appId: '1:568002325053:ios:262d2fbb82561459b01854',
    messagingSenderId: '568002325053',
    projectId: 'gitlauk-e752f',
    storageBucket: 'gitlauk-e752f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );


static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyCOtOZmZU_8nhg7RF5C5LW7cq-dpOVr-P4",
  authDomain: "gitlauk-e752f.firebaseapp.com",
  projectId: "gitlauk-e752f",
  storageBucket: "gitlauk-e752f.firebasestorage.app",
  messagingSenderId: "568002325053",
  appId: "1:568002325053:web:d7c078cff8a6e507b01854",
  measurementId: "G-KVDNB8S399",
);
}